name: business

dictionary_config: dict-0

topic_method: lsi
topic_config: lsi-0

train_method: svm
train_config: svm-0

business:
    dict-0:
        count_threshold: 2      # remove words that freq <= `count_threshold` in the whole dictionary 
        no_below: 5            # remove words that appear in less than `no_below` documents
        no_above: 0.8           # remove words that appear in more than `no_above`% documents
        keep_n: 100000000           
    
    lda-0:
        num_topics: 20
        chunksize: 80000
        alpha: 'auto'
        eta: 'auto'
        iterations: 100
        passes: 20
        eval_every: 0
        # workers: 4
    
    lsi-0:
        num_topics: 300
        # chunksize: 4000
        # power_iters: 10

    svm-0:

        kernel: rbf
        C: 0.2
        gamma: 1.
        is_unbalanced: true
        probability: false
        is_one_vs_rest: False
        n_jobs: 4
        is_test: true

    logistic-0:
        params:
            solver: lbfgs
            penalty: l2
            tol: 0.000001
            C: 1.
            dual: false
            n_jobs: 4
            max_iter: 1000

        is_unbalanced: false
        is_test: false
    

    xgb-0:
        max_depth: 10
        eta: 2
        silent: 1
        objective: binary:logistic
        n_thread: 4
        eval_metric: auc
        n_round: 100

make_doc:
    tmp_dir: ./data/jieba/                             # jieba缓存目录
    user_dict_path: ./data/jieba/specialword.dict     # 用户词典
    stop_words_path: ./data/jieba/stop_words.utf8      # 停用词
    idf_file_path: ./data/jieba/idf.utf8               # idf词典
    is_keyword: false
    len_threshold: 1