name: daily

dictionary_config: dict-0

topic_method: lda
topic_config: lda-0

train_method: svm
train_config: svm-0

daily:
    dict-0:
        count_threshold: 2      # remove words that freq <= `count_threshold` in the whole dictionary 
        no_below: 20            # remove words that appear in less than `no_below` documents
        no_above: 0.5
        keep_n: 100000000           # remove words that appear in more than `no_above`% documents
    
    lda-0:
        num_topics: 100
        chunksize: 80000
        alpha: 'auto'
        eta: 'auto'
        iterations: 100
        passes: 20
        eval_every: 0
        # workers: 4
    
    lsi-0:
        num_topics: 100
        # chunksize: 4000
        # power_iters: 10

    svm-0:

        kernel: rbf
        C: 20.
        gamma: 5.
        is_unbalanced: false
        probability: false
        is_one_vs_rest: False
        n_jobs: 4
        is_test: true

    logistic-0:
        penalty: l2
        C: 1.
        is_unbalanced: true

    xgb-0:
        max_depth: 10
        eta: 2
        silent: 1
        objective: binary:logistic
        n_thread: 4
        eval_metric: auc
        n_round: 100

make_doc:
    tmp_dir: ./data/jieba/                             # jieba缓存目录
    user_dict_path: ./data/jieba/specialword.dict     # 用户词典
    stop_words_path: ./data/jieba/stop_words.utf8      # 停用词
    idf_file_path: ./data/jieba/idf.utf8               # idf词典
    is_keyword: false
    len_threshold: 1